### ISSUE TITLE
Another fork ...

### ISSUE THREAD

**Issue by troglobit** [blueness/sthttpd#3]
Hi,

just wanted to let you know I've created another fork of thttpd, included all your patches and quite a few more: gzip deflate, keep-alive, and HTTPS using OpenSSL/LibreSSL.

https://github.com/troglobit/merecat

All the best
 /Joachim

**Comment by blueness** [comment]
not sure why we need another fork, but meh.  i did this because i got too much pushback from gentoo users who wanted to keep it going.  if the coverage on your fork is big enough to ensure you're not introducing regressions, i don't see why we shouldn't just switch over.  having said that, what is your fork providing the people should want?

**Comment by troglobit** [comment]
I wasn't really aiming for a "meh" ... but you're right, I have no test coverage to speak of, probably lots of regressions and there's a lot of other changes both big and small compared to the original. So likely nothing of interest to your users, sorry.
